import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <head>
        <title>Tarc Fitness</title>
        <link href="css/style.css" rel="stylesheet" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta
          content="info@tarc-fitness.de Tarc Fitness � Home � Gym � Kontakt; Shop. "
          name="description"
        />
        <meta content="text/html; charset=utf-8" httpEquiv="Content-Type" />
      </head>
      {children}
    </html>
  );
}
